### ISSUE TITLE
**`CheckList`**

### ISSUE THREAD

**Issue by PsychoPunkSage** [Lazychain/solidity-contracts#21]
# Contract Review and Testing Checklist

## 1. Apps
- [ ] `lottery.sol`

### Root Interfaces
- [ ] `ICementableTokenMetadata.sol`
- [ ] `ITokenMetadata.sol`

### Metadata Interfaces
- [ ] `ICementableTokenMetadata.sol`
- [ ] `IContractMetadata.sol`
- [ ] `ITokenMetadata.sol`
- [ ] `IUpdatableTokenMetadata.sol`

### Precompile Interfaces
- [ ] `IBase64.sol`
- [ ] `ICompress.sol`
- [ ] `IIntegers.sol`
- [ ] `IJsonStore.sol`
- [ ] `IJsonUtil.sol`
- [ ] `INativeMinter.sol`
- [ ] `IStrings.sol`

### Token Interfaces
- [ ] `IERC721Burnable.sol`
- [ ] `IERC721Mintable.sol`

## 3. Metadata
- [ ] `CementableTokenMetadata.sol`
- [ ] `ContractMetadata.sol`
- [ ] `TokenMetadataReader.sol`
- [ ] `TokenMetadata.sol`
- [ ] `UpdatableTokenMetadata.sol`

### ERC721 Contracts
- [ ] `ERC721Base.sol`
- [ ] `ERC721Cementable.sol`
- [ ] `ERC721.sol`
- [ ] `ERC721Updatable.sol`

### Other Contracts
- [ ] `Types.sol`

### Metadata Contracts
- [ ] `CementableTokenMetadataUpgradeable.sol`
- [ ] `ContractMetadataUpgradeable.sol`
- [ ] `TokenMetadataUpgradeable.sol`
- [ ] `UpdatableTokenMetadataUpgradeable.sol`

### ERC721 Contracts
- [ ] `ERC721BaseUpgradeable.sol`
- [ ] `ERC721CementableUpgradeable.sol`
- [ ] `ERC721UpdatableUpgradeable.sol`
- [ ] `ERC721Upgradeable.sol`

## 6. Utilities
- [X] `Base64.sol`
- [ ] `CompressedJSON.sol`
- [ ] `Compress.sol`
- [ ] `Integers.sol`
- [X] `JsonParser.sol`
- [X] `JsonStore.sol`
- [X] `JsonUtil.sol`
- [ ] `PriorityQueue.sol`
- [ ] `Strings.sol`

---

## Additional Tasks
- [ ] Ensure proper documentation is provided for each file.
- [ ] Write unit tests for all contracts and interfaces.
- [ ] Verify coverage reports for each contract.
- [ ] Confirm adherence to coding standards and security best practices.
- [ ] Audit dependency libraries used in the `utils` directory.
